[package]
name = "api-client"
version = "0.1.0"
edition = "2021"

[dependencies]
models = { version = "0.1.0", path = "../../../models" }
reqwest = { version = "0.12.2", default-features = false, features = ["json"] }
thiserror = "1.0.58"
